import { useEffect, useMemo, useRef, useState } from 'react';

// ─── Emoji data ────────────────────────────────────────────────────────────────
// Each entry: [char, ...keywords]
type EmojiEntry = { char: string; name: string; keywords: string[] };

const RAW: [string, string, ...string[]][] = [
  // Smileys & Emotion
  ['😀', 'grinning face', 'happy', 'smile'],
  ['😃', 'grinning face with big eyes', 'happy', 'joy'],
  ['😄', 'grinning face with smiling eyes', 'happy', 'haha'],
  ['😁', 'beaming face with smiling eyes', 'grin'],
  ['😆', 'grinning squinting face', 'laugh', 'lol'],
  ['😅', 'grinning face with sweat', 'sweat', 'nervous'],
  ['🤣', 'rolling on the floor laughing', 'rofl', 'lmao'],
  ['😂', 'face with tears of joy', 'lol', 'cry', 'laugh'],
  ['🙂', 'slightly smiling face', 'smile'],
  ['🙃', 'upside-down face', 'silly'],
  ['😉', 'winking face', 'wink', 'flirt'],
  ['😊', 'smiling face with smiling eyes', 'blush', 'happy'],
  ['😇', 'smiling face with halo', 'angel', 'innocent'],
  ['🥰', 'smiling face with hearts', 'love', 'adore'],
  ['😍', 'smiling face with heart-eyes', 'love', 'crush'],
  ['🤩', 'star-struck', 'wow', 'amazing'],
  ['😘', 'face blowing a kiss', 'kiss', 'love'],
  ['😗', 'kissing face', 'kiss'],
  ['😚', 'kissing face with closed eyes', 'kiss'],
  ['😙', 'kissing face with smiling eyes', 'kiss'],
  ['🥲', 'smiling face with tear', 'sad', 'happy'],
  ['😋', 'face savoring food', 'yum', 'hungry'],
  ['😛', 'face with tongue', 'tongue', 'silly'],
  ['😜', 'winking face with tongue', 'tongue', 'silly'],
  ['🤪', 'zany face', 'crazy', 'wild'],
  ['😝', 'squinting face with tongue', 'tongue'],
  ['🤑', 'money-mouth face', 'money', 'rich'],
  ['🤗', 'smiling face with open hands', 'hug'],
  ['🤭', 'face with hand over mouth', 'shh', 'giggle'],
  ['🤫', 'shushing face', 'quiet', 'shhh'],
  ['🤔', 'thinking face', 'think', 'hmm'],
  ['🤐', 'zipper-mouth face', 'silent', 'zipped'],
  ['🤨', 'face with raised eyebrow', 'suspicious', 'really'],
  ['😐', 'neutral face', 'neutral', 'meh'],
  ['😑', 'expressionless face', 'blank'],
  ['😶', 'face without mouth', 'silent'],
  ['😏', 'smirking face', 'smirk', 'sly'],
  ['😒', 'unamused face', 'meh', 'boring'],
  ['🙄', 'face with rolling eyes', 'eye roll', 'whatever'],
  ['😬', 'grimacing face', 'grimace', 'awkward'],
  ['🤥', 'lying face', 'liar', 'pinocchio'],
  ['😌', 'relieved face', 'calm', 'relief'],
  ['😔', 'pensive face', 'sad', 'thoughtful'],
  ['😪', 'sleepy face', 'tired', 'sleep'],
  ['🤤', 'drooling face', 'drool', 'hungry'],
  ['😴', 'sleeping face', 'sleep', 'zzz'],
  ['😷', 'face with medical mask', 'sick', 'mask'],
  ['🤒', 'face with thermometer', 'sick', 'ill'],
  ['🤕', 'face with head-bandage', 'hurt', 'injured'],
  ['🤢', 'nauseated face', 'sick', 'gross'],
  ['🤮', 'face vomiting', 'puke', 'sick'],
  ['🤧', 'sneezing face', 'sneeze', 'sick'],
  ['🥵', 'hot face', 'hot', 'sweating'],
  ['🥶', 'cold face', 'cold', 'freezing'],
  ['🥴', 'woozy face', 'dizzy', 'drunk'],
  ['😵', 'dizzy face', 'dizzy', 'dead'],
  ['🤯', 'exploding head', 'mind blown', 'shocked'],
  ['🤠', 'cowboy hat face', 'cowboy', 'western'],
  ['🥳', 'partying face', 'party', 'celebrate'],
  ['🥸', 'disguised face', 'disguise', 'incognito'],
  ['😎', 'smiling face with sunglasses', 'cool', 'sunglasses'],
  ['🤓', 'nerd face', 'nerd', 'geek'],
  ['🧐', 'face with monocle', 'suspicious', 'curious'],
  ['😕', 'confused face', 'confused', 'unsure'],
  ['😟', 'worried face', 'worried', 'concern'],
  ['🙁', 'slightly frowning face', 'sad'],
  ['☹️', 'frowning face', 'sad', 'unhappy'],
  ['😮', 'face with open mouth', 'surprised', 'wow'],
  ['😯', 'hushed face', 'surprised', 'quiet'],
  ['😲', 'astonished face', 'shocked', 'wow'],
  ['😳', 'flushed face', 'embarrassed', 'blush'],
  ['🥺', 'pleading face', 'puppy eyes', 'please'],
  ['😦', 'frowning face with open mouth', 'worried'],
  ['😧', 'anguished face', 'shocked'],
  ['😨', 'fearful face', 'scared', 'fear'],
  ['😰', 'anxious face with sweat', 'nervous', 'worried'],
  ['😥', 'sad but relieved face', 'sad', 'relieved'],
  ['😢', 'crying face', 'cry', 'sad', 'tear'],
  ['😭', 'loudly crying face', 'cry', 'sob', 'sad'],
  ['😱', 'face screaming in fear', 'scream', 'scared'],
  ['😖', 'confounded face', 'frustrated'],
  ['😣', 'persevering face', 'struggling'],
  ['😞', 'disappointed face', 'sad', 'disappointed'],
  ['😓', 'downcast face with sweat', 'stressed'],
  ['😩', 'weary face', 'tired', 'exhausted'],
  ['😫', 'tired face', 'exhausted', 'worn out'],
  ['🥱', 'yawning face', 'yawn', 'tired', 'bored'],
  ['😤', 'face with steam from nose', 'angry', 'triumph'],
  ['😡', 'enraged face', 'angry', 'mad'],
  ['😠', 'angry face', 'angry', 'grumpy'],
  ['🤬', 'face with symbols on mouth', 'angry', 'swearing'],
  ['😈', 'smiling face with horns', 'devil', 'evil'],
  ['👿', 'angry face with horns', 'devil', 'angry'],
  ['💀', 'skull', 'dead', 'death'],
  ['☠️', 'skull and crossbones', 'dead', 'danger'],
  ['💩', 'pile of poo', 'poop', 'crap'],
  ['🤡', 'clown face', 'clown'],
  ['👹', 'ogre', 'monster'],
  ['👺', 'goblin', 'monster'],
  ['👻', 'ghost', 'halloween', 'spooky'],
  ['👽', 'alien', 'ufo', 'space'],
  ['👾', 'alien monster', 'game', 'pixel'],
  ['🤖', 'robot', 'bot', 'machine'],
  ['😺', 'grinning cat', 'cat', 'happy'],
  ['😸', 'grinning cat with smiling eyes', 'cat'],
  ['😹', 'cat with tears of joy', 'cat', 'laugh'],
  ['😻', 'smiling cat with heart-eyes', 'cat', 'love'],
  ['😼', 'cat with wry smile', 'cat', 'smirk'],
  ['😽', 'kissing cat', 'cat', 'kiss'],
  ['🙀', 'weary cat', 'cat', 'shocked'],
  ['😿', 'crying cat', 'cat', 'sad'],
  ['😾', 'pouting cat', 'cat', 'angry'],

  // People & Hands
  ['👋', 'waving hand', 'wave', 'hello', 'bye'],
  ['🤚', 'raised back of hand', 'hand', 'stop'],
  ['🖐️', 'hand with fingers splayed', 'hand', 'five'],
  ['✋', 'raised hand', 'stop', 'high five'],
  ['🖖', 'vulcan salute', 'spock', 'live long'],
  ['👌', 'ok hand', 'ok', 'perfect'],
  ['🤌', 'pinched fingers', 'italian', 'chef'],
  ['🤏', 'pinching hand', 'small', 'tiny'],
  ['✌️', 'victory hand', 'peace', 'two'],
  ['🤞', 'crossed fingers', 'luck', 'hope'],
  ['🤟', 'love-you gesture', 'love', 'ily'],
  ['🤘', 'sign of the horns', 'rock', 'metal'],
  ['🤙', 'call me hand', 'call', 'phone', 'shaka'],
  ['👈', 'backhand index pointing left', 'point', 'left'],
  ['👉', 'backhand index pointing right', 'point', 'right'],
  ['👆', 'backhand index pointing up', 'point', 'up'],
  ['🖕', 'middle finger', 'rude'],
  ['👇', 'backhand index pointing down', 'point', 'down'],
  ['☝️', 'index pointing up', 'one', 'point'],
  ['👍', 'thumbs up', 'like', 'good', 'yes'],
  ['👎', 'thumbs down', 'dislike', 'bad', 'no'],
  ['✊', 'raised fist', 'fist', 'power'],
  ['👊', 'oncoming fist', 'punch', 'fist'],
  ['🤛', 'left-facing fist', 'fist bump'],
  ['🤜', 'right-facing fist', 'fist bump'],
  ['👏', 'clapping hands', 'clap', 'applause'],
  ['🙌', 'raising hands', 'celebrate', 'praise'],
  ['👐', 'open hands', 'open', 'hug'],
  ['🤲', 'palms up together', 'prayer', 'please'],
  ['🤝', 'handshake', 'deal', 'agree'],
  ['🙏', 'folded hands', 'pray', 'please', 'thanks'],
  ['✍️', 'writing hand', 'write'],
  ['💅', 'nail polish', 'nails', 'manicure'],
  ['🤳', 'selfie', 'selfie', 'photo'],
  ['💪', 'flexed biceps', 'strong', 'muscle', 'flex'],
  ['🦾', 'mechanical arm', 'robot', 'prosthetic'],
  ['🦵', 'leg', 'kick'],
  ['🦶', 'foot', 'kick'],
  ['👂', 'ear', 'listen', 'hear'],
  ['👃', 'nose', 'smell'],
  ['🧠', 'brain', 'smart', 'think'],
  ['🫀', 'anatomical heart', 'heart', 'organ'],
  ['🫁', 'lungs', 'breathe'],
  ['🦷', 'tooth', 'dental'],
  ['🦴', 'bone', 'skeleton'],
  ['👀', 'eyes', 'look', 'see'],
  ['👁️', 'eye', 'look', 'see'],
  ['👅', 'tongue', 'taste', 'lick'],
  ['👄', 'mouth', 'lips', 'kiss'],
  ['👶', 'baby', 'infant', 'child'],
  ['🧒', 'child', 'kid'],
  ['👦', 'boy', 'child', 'male'],
  ['👧', 'girl', 'child', 'female'],
  ['🧑', 'person', 'human'],
  ['👱', 'person with blonde hair', 'blond'],
  ['👨', 'man', 'male', 'person'],
  ['🧔', 'person with beard', 'beard'],
  ['👩', 'woman', 'female', 'person'],
  ['🧓', 'older person', 'elderly'],
  ['👴', 'old man', 'grandpa', 'elderly'],
  ['👵', 'old woman', 'grandma', 'elderly'],

  // Nature & Animals
  ['🐶', 'dog face', 'dog', 'puppy', 'pet'],
  ['🐱', 'cat face', 'cat', 'kitty', 'pet'],
  ['🐭', 'mouse face', 'mouse'],
  ['🐹', 'hamster', 'hamster', 'pet'],
  ['🐰', 'rabbit face', 'rabbit', 'bunny'],
  ['🦊', 'fox', 'fox', 'clever'],
  ['🐻', 'bear', 'bear'],
  ['🐼', 'panda', 'panda'],
  ['🐨', 'koala', 'koala', 'australia'],
  ['🐯', 'tiger face', 'tiger'],
  ['🦁', 'lion', 'lion', 'king'],
  ['🐮', 'cow face', 'cow'],
  ['🐷', 'pig face', 'pig', 'oink'],
  ['🐸', 'frog', 'frog', 'kermit'],
  ['🐵', 'monkey face', 'monkey'],
  ['🙈', 'see-no-evil monkey', 'see no evil'],
  ['🙉', 'hear-no-evil monkey', 'hear no evil'],
  ['🙊', 'speak-no-evil monkey', 'speak no evil'],
  ['🐔', 'chicken', 'chicken', 'hen'],
  ['🐧', 'penguin', 'penguin', 'cold'],
  ['🐦', 'bird', 'bird', 'tweet'],
  ['🦆', 'duck', 'duck', 'quack'],
  ['🦅', 'eagle', 'eagle', 'freedom'],
  ['🦉', 'owl', 'owl', 'wise'],
  ['🦇', 'bat', 'bat', 'vampire'],
  ['🐺', 'wolf', 'wolf'],
  ['🐗', 'boar', 'boar', 'pig'],
  ['🐴', 'horse face', 'horse'],
  ['🦄', 'unicorn', 'unicorn', 'magic'],
  ['🐝', 'honeybee', 'bee', 'honey'],
  ['🐛', 'bug', 'bug', 'caterpillar'],
  ['🦋', 'butterfly', 'butterfly', 'beautiful'],
  ['🐌', 'snail', 'snail', 'slow'],
  ['🐞', 'ladybug', 'ladybug', 'luck'],
  ['🐜', 'ant', 'ant'],
  ['🦟', 'mosquito', 'mosquito', 'bug'],
  ['🦂', 'scorpion', 'scorpion'],
  ['🐢', 'turtle', 'turtle', 'slow'],
  ['🐍', 'snake', 'snake', 'slither'],
  ['🦎', 'lizard', 'lizard'],
  ['🦖', 'T-Rex', 'dinosaur', 'trex'],
  ['🦕', 'sauropod', 'dinosaur', 'brontosaurus'],
  ['🐊', 'crocodile', 'croc', 'alligator'],
  ['🦈', 'shark', 'shark', 'fish'],
  ['🐋', 'whale', 'whale'],
  ['🐬', 'dolphin', 'dolphin'],
  ['🦭', 'seal', 'seal'],
  ['🐟', 'fish', 'fish'],
  ['🐠', 'tropical fish', 'fish', 'colorful'],
  ['🦑', 'squid', 'squid'],
  ['🦞', 'lobster', 'lobster'],
  ['🦀', 'crab', 'crab'],
  ['🐙', 'octopus', 'octopus'],
  ['🦓', 'zebra', 'zebra'],
  ['🦒', 'giraffe', 'giraffe'],
  ['🦘', 'kangaroo', 'kangaroo', 'australia'],
  ['🦛', 'hippopotamus', 'hippo'],
  ['🐘', 'elephant', 'elephant'],
  ['🦏', 'rhinoceros', 'rhino'],
  ['🐪', 'camel', 'camel', 'desert'],
  ['🦙', 'llama', 'llama'],
  ['🦍', 'gorilla', 'gorilla', 'ape'],
  ['🐓', 'rooster', 'rooster', 'cock'],
  ['🦚', 'peacock', 'peacock'],
  ['🌵', 'cactus', 'cactus', 'desert'],
  ['🌲', 'evergreen tree', 'tree', 'pine'],
  ['🌳', 'deciduous tree', 'tree'],
  ['🌴', 'palm tree', 'palm', 'beach'],
  ['🌱', 'seedling', 'plant', 'sprout'],
  ['🌿', 'herb', 'leaf', 'green'],
  ['☘️', 'shamrock', 'clover', 'luck', 'ireland'],
  ['🍀', 'four leaf clover', 'luck', 'clover'],
  ['🎋', 'tanabata tree', 'bamboo'],
  ['🍃', 'leaf fluttering in wind', 'leaf'],
  ['🍂', 'fallen leaf', 'leaf', 'autumn'],
  ['🍁', 'maple leaf', 'leaf', 'autumn', 'canada'],
  ['🍄', 'mushroom', 'mushroom', 'fungi'],
  ['🌾', 'sheaf of rice', 'grain', 'wheat'],
  ['💐', 'bouquet', 'flowers', 'bouquet'],
  ['🌷', 'tulip', 'flower', 'tulip'],
  ['🌹', 'rose', 'rose', 'love', 'flower'],
  ['🥀', 'wilted flower', 'dead', 'sad'],
  ['🌺', 'hibiscus', 'flower', 'tropical'],
  ['🌸', 'cherry blossom', 'flower', 'japan', 'spring'],
  ['🌼', 'blossom', 'flower', 'yellow'],
  ['🌻', 'sunflower', 'sunflower', 'happy'],
  ['🌞', 'sun with face', 'sun', 'happy'],
  ['🌝', 'full moon face', 'moon'],
  ['🌛', 'first quarter moon face', 'moon'],
  ['🌜', 'last quarter moon face', 'moon'],
  ['🌚', 'new moon face', 'moon', 'dark'],
  ['🌕', 'full moon', 'moon'],
  ['🌖', 'waning gibbous moon', 'moon'],
  ['🌗', 'last quarter moon', 'moon'],
  ['🌘', 'waning crescent moon', 'moon'],
  ['🌑', 'new moon', 'moon', 'dark'],
  ['🌒', 'waxing crescent moon', 'moon'],
  ['🌓', 'first quarter moon', 'moon'],
  ['🌔', 'waxing gibbous moon', 'moon'],
  ['🌙', 'crescent moon', 'moon', 'night'],
  ['🌟', 'glowing star', 'star', 'shine'],
  ['⭐', 'star', 'star'],
  ['🌈', 'rainbow', 'rainbow', 'colorful'],
  ['☁️', 'cloud', 'cloud', 'weather'],
  ['⛅', 'sun behind cloud', 'partly cloudy'],
  ['🌤️', 'sun behind small cloud', 'mostly sunny'],
  ['🌦️', 'sun behind rain cloud', 'rain'],
  ['🌧️', 'cloud with rain', 'rain'],
  ['⛈️', 'cloud with lightning and rain', 'storm', 'thunder'],
  ['🌩️', 'cloud with lightning', 'lightning', 'storm'],
  ['🌨️', 'cloud with snow', 'snow'],
  ['❄️', 'snowflake', 'snow', 'cold', 'winter'],
  ['☃️', 'snowman', 'snowman', 'winter'],
  ['⛄', 'snowman without snow', 'snowman'],
  ['🌬️', 'wind face', 'wind', 'blow'],
  ['💨', 'dashing away', 'wind', 'fast'],
  ['💧', 'droplet', 'water', 'drop'],
  ['💦', 'sweat droplets', 'water', 'splash'],
  ['🌊', 'water wave', 'wave', 'ocean', 'sea'],
  ['🔥', 'fire', 'fire', 'hot', 'flame'],
  ['⚡', 'lightning', 'lightning', 'electric', 'thunder'],
  ['🌍', 'globe europe-africa', 'earth', 'world'],
  ['🌎', 'globe americas', 'earth', 'world'],
  ['🌏', 'globe asia-australia', 'earth', 'world'],
  ['🪐', 'ringed planet', 'planet', 'saturn'],
  ['💫', 'dizzy', 'star', 'sparkle'],
  ['⚫', 'black circle', 'circle', 'black'],
  ['🌀', 'cyclone', 'cyclone', 'spiral'],

  // Food & Drink
  ['🍎', 'red apple', 'apple', 'fruit'],
  ['🍊', 'tangerine', 'orange', 'fruit'],
  ['🍋', 'lemon', 'lemon', 'sour'],
  ['🍇', 'grapes', 'grapes', 'fruit'],
  ['🍓', 'strawberry', 'strawberry', 'fruit'],
  ['🫐', 'blueberries', 'blueberry', 'fruit'],
  ['🍈', 'melon', 'melon'],
  ['🍉', 'watermelon', 'watermelon', 'summer'],
  ['🍑', 'peach', 'peach', 'fruit'],
  ['🍒', 'cherries', 'cherry', 'fruit'],
  ['🍌', 'banana', 'banana', 'fruit'],
  ['🍍', 'pineapple', 'pineapple', 'tropical'],
  ['🥭', 'mango', 'mango', 'tropical'],
  ['🥥', 'coconut', 'coconut', 'tropical'],
  ['🥝', 'kiwi fruit', 'kiwi'],
  ['🍅', 'tomato', 'tomato'],
  ['🫒', 'olive', 'olive'],
  ['🥑', 'avocado', 'avocado', 'guac'],
  ['🍆', 'eggplant', 'eggplant', 'aubergine'],
  ['🥦', 'broccoli', 'broccoli'],
  ['🥬', 'leafy green', 'vegetable', 'lettuce'],
  ['🥒', 'cucumber', 'cucumber'],
  ['🌽', 'ear of corn', 'corn', 'maize'],
  ['🌶️', 'hot pepper', 'spicy', 'chili'],
  ['🫑', 'bell pepper', 'pepper'],
  ['🥕', 'carrot', 'carrot'],
  ['🧅', 'onion', 'onion'],
  ['🧄', 'garlic', 'garlic'],
  ['🥔', 'potato', 'potato'],
  ['🍠', 'roasted sweet potato', 'sweet potato'],
  ['🥐', 'croissant', 'croissant', 'french'],
  ['🥖', 'baguette bread', 'bread', 'french'],
  ['🍞', 'bread', 'bread', 'toast'],
  ['🧀', 'cheese wedge', 'cheese'],
  ['🥚', 'egg', 'egg'],
  ['🍳', 'cooking', 'frying pan', 'egg'],
  ['🥓', 'bacon', 'bacon'],
  ['🥞', 'pancakes', 'pancakes', 'breakfast'],
  ['🧇', 'waffle', 'waffle'],
  ['🍗', 'poultry leg', 'chicken', 'meat'],
  ['🍖', 'meat on bone', 'meat'],
  ['🌮', 'taco', 'taco', 'mexican'],
  ['🌯', 'burrito', 'burrito', 'mexican'],
  ['🥙', 'stuffed flatbread', 'wrap', 'sandwich'],
  ['🧆', 'falafel', 'falafel'],
  ['🥗', 'green salad', 'salad', 'healthy'],
  ['🍜', 'steaming bowl', 'noodles', 'ramen'],
  ['🍝', 'spaghetti', 'pasta', 'italian'],
  ['🍛', 'curry rice', 'curry', 'indian'],
  ['🍣', 'sushi', 'sushi', 'japanese'],
  ['🍱', 'bento box', 'bento', 'japanese'],
  ['🍔', 'hamburger', 'burger', 'fast food'],
  ['🍟', 'french fries', 'fries', 'fast food'],
  ['🍕', 'pizza', 'pizza', 'italian'],
  ['🌭', 'hot dog', 'hotdog'],
  ['🍿', 'popcorn', 'popcorn', 'movie'],
  ['🧂', 'salt', 'salt'],
  ['🍦', 'soft ice cream', 'ice cream', 'dessert'],
  ['🍧', 'shaved ice', 'ice', 'dessert'],
  ['🍨', 'ice cream', 'ice cream'],
  ['🍩', 'doughnut', 'donut', 'dessert'],
  ['🍪', 'cookie', 'cookie', 'dessert'],
  ['🎂', 'birthday cake', 'cake', 'birthday'],
  ['🍰', 'shortcake', 'cake', 'dessert'],
  ['🧁', 'cupcake', 'cupcake', 'dessert'],
  ['🍫', 'chocolate bar', 'chocolate'],
  ['🍬', 'candy', 'candy', 'sweet'],
  ['🍭', 'lollipop', 'lollipop', 'candy'],
  ['☕', 'hot beverage', 'coffee', 'tea', 'hot'],
  ['🍵', 'teacup without handle', 'tea', 'hot'],
  ['🧃', 'beverage box', 'juice', 'drink'],
  ['🥤', 'cup with straw', 'soda', 'drink'],
  ['🧋', 'bubble tea', 'boba', 'tea'],
  ['🍺', 'beer mug', 'beer', 'drink'],
  ['🍻', 'clinking beer mugs', 'cheers', 'beer'],
  ['🥂', 'clinking glasses', 'champagne', 'cheers'],
  ['🍷', 'wine glass', 'wine'],
  ['🥃', 'tumbler glass', 'whiskey', 'drink'],
  ['🍹', 'tropical drink', 'cocktail', 'drink'],
  ['🧉', 'mate', 'mate', 'tea'],
  ['🍾', 'bottle with popping cork', 'champagne', 'celebrate'],
  ['🧊', 'ice', 'ice', 'cold'],
  ['🍴', 'fork and knife', 'utensil', 'eat'],
  ['🥄', 'spoon', 'spoon', 'eat'],

  // Activities & Sports
  ['⚽', 'soccer ball', 'soccer', 'football', 'sport'],
  ['🏀', 'basketball', 'basketball', 'sport'],
  ['🏈', 'american football', 'football', 'sport'],
  ['⚾', 'baseball', 'baseball', 'sport'],
  ['🥎', 'softball', 'softball', 'sport'],
  ['🎾', 'tennis', 'tennis', 'sport'],
  ['🏐', 'volleyball', 'volleyball', 'sport'],
  ['🏉', 'rugby football', 'rugby', 'sport'],
  ['🎱', 'pool 8 ball', 'billiards', 'pool'],
  ['🏓', 'ping pong', 'table tennis', 'sport'],
  ['🏸', 'badminton', 'badminton', 'sport'],
  ['🏒', 'ice hockey', 'hockey', 'sport'],
  ['🏑', 'field hockey', 'hockey'],
  ['🏏', 'cricket game', 'cricket'],
  ['🥍', 'lacrosse', 'lacrosse'],
  ['⛳', 'flag in hole', 'golf', 'sport'],
  ['🎣', 'fishing pole', 'fishing'],
  ['🤿', 'diving mask', 'scuba', 'dive'],
  ['🎽', 'running shirt', 'sport', 'running'],
  ['🎿', 'skis', 'skiing', 'snow', 'sport'],
  ['🛷', 'sled', 'sled', 'winter'],
  ['🥌', 'curling stone', 'curling'],
  ['🏆', 'trophy', 'trophy', 'win', 'award'],
  ['🥇', 'first place medal', 'gold', 'winner', 'first'],
  ['🥈', 'second place medal', 'silver', 'second'],
  ['🥉', 'third place medal', 'bronze', 'third'],
  ['🎖️', 'military medal', 'medal', 'award'],
  ['🎗️', 'reminder ribbon', 'ribbon', 'awareness'],
  ['🎫', 'ticket', 'ticket', 'event'],
  ['🎪', 'circus tent', 'circus', 'fun'],
  ['🎭', 'performing arts', 'theater', 'arts'],
  ['🎨', 'artist palette', 'art', 'paint'],
  ['🎬', 'clapper board', 'movie', 'film'],
  ['🎤', 'microphone', 'mic', 'sing', 'music'],
  ['🎧', 'headphone', 'headphones', 'music', 'listen'],
  ['🎼', 'musical score', 'music', 'notes'],
  ['🎵', 'musical note', 'music', 'note', 'song'],
  ['🎶', 'musical notes', 'music', 'notes', 'song'],
  ['🎸', 'guitar', 'guitar', 'music', 'rock'],
  ['🎹', 'musical keyboard', 'piano', 'keyboard', 'music'],
  ['🎺', 'trumpet', 'trumpet', 'music'],
  ['🎻', 'violin', 'violin', 'music'],
  ['🥁', 'drum', 'drums', 'music'],
  ['🪘', 'long drum', 'drum', 'music'],
  ['🎲', 'game die', 'dice', 'random', 'game'],
  ['🎮', 'video game', 'game', 'controller', 'gaming'],
  ['🕹️', 'joystick', 'joystick', 'game', 'arcade'],
  ['🎰', 'slot machine', 'casino', 'slots'],
  ['🎯', 'bullseye', 'target', 'dart'],
  ['🪄', 'magic wand', 'magic', 'wand'],
  ['🃏', 'joker', 'card', 'joker'],
  ['🎴', 'flower playing cards', 'cards', 'game'],
  ['🀄', 'mahjong red dragon', 'mahjong'],
  ['🎳', 'bowling', 'bowling', 'sport'],

  // Travel & Places
  ['✈️', 'airplane', 'plane', 'fly', 'travel'],
  ['🚀', 'rocket', 'rocket', 'space', 'launch'],
  ['🛸', 'flying saucer', 'ufo', 'alien'],
  ['🚁', 'helicopter', 'helicopter'],
  ['🚂', 'locomotive', 'train', 'steam'],
  ['🚃', 'railway car', 'train'],
  ['🚄', 'high-speed train', 'shinkansen', 'fast'],
  ['🚅', 'bullet train', 'bullet train', 'fast'],
  ['🚇', 'metro', 'subway', 'metro'],
  ['🚌', 'bus', 'bus'],
  ['🚎', 'trolleybus', 'trolley'],
  ['🚐', 'minibus', 'van'],
  ['🚑', 'ambulance', 'ambulance', 'emergency'],
  ['🚒', 'fire engine', 'firetruck', 'emergency'],
  ['🚓', 'police car', 'police', 'cop'],
  ['🚕', 'taxi', 'taxi', 'cab'],
  ['🚗', 'automobile', 'car', 'drive'],
  ['🚙', 'sport utility vehicle', 'suv', 'car'],
  ['🚚', 'delivery truck', 'truck', 'delivery'],
  ['🏎️', 'racing car', 'race car', 'fast'],
  ['🏍️', 'motorcycle', 'motorcycle', 'bike'],
  ['🛵', 'motor scooter', 'scooter'],
  ['🚲', 'bicycle', 'bike', 'cycle'],
  ['🛴', 'kick scooter', 'scooter'],
  ['🛹', 'skateboard', 'skateboard'],
  ['🛺', 'auto rickshaw', 'rickshaw'],
  ['🚤', 'speedboat', 'boat', 'speed'],
  ['⛵', 'sailboat', 'sailing', 'boat'],
  ['🚢', 'ship', 'ship', 'boat'],
  ['⛽', 'fuel pump', 'gas', 'fuel'],
  ['🚦', 'vertical traffic light', 'traffic', 'stop'],
  ['🚥', 'horizontal traffic light', 'traffic'],
  ['🗺️', 'world map', 'map', 'world'],
  ['🧭', 'compass', 'compass', 'direction'],
  ['🌋', 'volcano', 'volcano', 'lava'],
  ['🏔️', 'snow-capped mountain', 'mountain', 'snow'],
  ['⛰️', 'mountain', 'mountain'],
  ['🗻', 'mount fuji', 'fuji', 'japan'],
  ['🏕️', 'camping', 'camping', 'tent'],
  ['🏖️', 'beach with umbrella', 'beach', 'summer'],
  ['🏗️', 'building construction', 'construction'],
  ['🏘️', 'houses', 'neighborhood'],
  ['🏚️', 'derelict house', 'abandoned'],
  ['🏠', 'house', 'home', 'house'],
  ['🏡', 'house with garden', 'home', 'garden'],
  ['🏢', 'office building', 'office', 'building'],
  ['🏣', 'Japanese post office', 'post office'],
  ['🏦', 'bank', 'bank', 'money'],
  ['🏨', 'hotel', 'hotel', 'stay'],
  ['🏫', 'school', 'school', 'education'],
  ['🏬', 'department store', 'store', 'shop'],
  ['🏭', 'factory', 'factory', 'industrial'],
  ['🏯', 'Japanese castle', 'castle', 'japan'],
  ['🏰', 'castle', 'castle', 'medieval'],
  ['💒', 'wedding', 'wedding', 'church'],
  ['🗼', 'Tokyo tower', 'tower', 'japan'],
  ['🗽', 'Statue of Liberty', 'liberty', 'usa'],
  ['⛪', 'church', 'church', 'religion'],
  ['🕌', 'mosque', 'mosque', 'islam'],
  ['🛕', 'hindu temple', 'temple', 'hindu'],
  ['🕍', 'synagogue', 'synagogue', 'jewish'],
  ['⛩️', 'shinto shrine', 'shrine', 'japan'],
  ['🌁', 'foggy', 'fog', 'misty'],
  ['🌃', 'night with stars', 'night', 'city'],
  ['🌆', 'cityscape at dusk', 'city', 'dusk'],
  ['🌇', 'sunset', 'sunset', 'city'],
  ['🌉', 'bridge at night', 'bridge', 'night'],
  ['🎠', 'carousel horse', 'carousel', 'fair'],
  ['🎡', 'ferris wheel', 'ferris wheel', 'fair'],
  ['🎢', 'roller coaster', 'roller coaster', 'fun'],
  ['🎪', 'circus tent', 'circus'],
  ['🗿', 'moai', 'statue', 'easter island'],

  // Objects
  ['💡', 'light bulb', 'idea', 'light', 'bulb'],
  ['🔦', 'flashlight', 'flashlight', 'torch'],
  ['🕯️', 'candle', 'candle', 'light'],
  ['🖥️', 'desktop computer', 'computer', 'desktop'],
  ['💻', 'laptop', 'laptop', 'computer'],
  ['⌨️', 'keyboard', 'keyboard', 'type'],
  ['🖱️', 'computer mouse', 'mouse'],
  ['🖨️', 'printer', 'printer', 'print'],
  ['📱', 'mobile phone', 'phone', 'mobile'],
  ['📞', 'telephone receiver', 'phone', 'call'],
  ['☎️', 'telephone', 'phone', 'old'],
  ['📟', 'pager', 'pager', 'beeper'],
  ['📠', 'fax machine', 'fax'],
  ['📺', 'television', 'tv', 'television'],
  ['📻', 'radio', 'radio'],
  ['🎙️', 'studio microphone', 'mic', 'studio'],
  ['⏰', 'alarm clock', 'alarm', 'clock'],
  ['⌚', 'watch', 'watch', 'time'],
  ['📷', 'camera', 'camera', 'photo'],
  ['📸', 'camera with flash', 'camera', 'photo', 'flash'],
  ['📹', 'video camera', 'video', 'camera'],
  ['🔭', 'telescope', 'telescope', 'space'],
  ['🔬', 'microscope', 'microscope', 'science'],
  ['💊', 'pill', 'pill', 'medicine'],
  ['💉', 'syringe', 'syringe', 'injection'],
  ['🩹', 'adhesive bandage', 'bandaid', 'wound'],
  ['🩺', 'stethoscope', 'doctor', 'health'],
  ['🧪', 'test tube', 'science', 'experiment'],
  ['🧫', 'petri dish', 'science', 'bacteria'],
  ['🧬', 'dna', 'dna', 'biology', 'science'],
  ['🧲', 'magnet', 'magnet', 'attract'],
  ['🔋', 'battery', 'battery', 'power'],
  ['🔌', 'electric plug', 'plug', 'power'],
  ['💾', 'floppy disk', 'disk', 'save'],
  ['💿', 'optical disk', 'cd', 'disc'],
  ['📀', 'dvd', 'dvd', 'disc'],
  ['📼', 'videocassette', 'vhs', 'tape'],
  ['📡', 'satellite antenna', 'satellite', 'signal'],
  ['🔑', 'key', 'key', 'lock'],
  ['🗝️', 'old key', 'key', 'old'],
  ['🔐', 'locked with key', 'locked', 'security'],
  ['🔒', 'locked', 'lock', 'secure'],
  ['🔓', 'unlocked', 'unlock', 'open'],
  ['🔨', 'hammer', 'hammer', 'tool'],
  ['🪛', 'screwdriver', 'screwdriver', 'tool'],
  ['🪚', 'carpentry saw', 'saw', 'tool'],
  ['🔧', 'wrench', 'wrench', 'tool'],
  ['🪤', 'mouse trap', 'trap'],
  ['🗡️', 'dagger', 'dagger', 'sword'],
  ['⚔️', 'crossed swords', 'sword', 'fight'],
  ['🛡️', 'shield', 'shield', 'protect'],
  ['🔫', 'water pistol', 'gun', 'squirt'],
  ['🪃', 'boomerang', 'boomerang'],
  ['🪝', 'hook', 'hook'],
  ['🧲', 'magnet', 'magnet'],
  ['🔩', 'nut and bolt', 'bolt', 'screw'],
  ['⚙️', 'gear', 'gear', 'settings', 'cog'],
  ['🗜️', 'clamp', 'clamp'],
  ['🪜', 'ladder', 'ladder'],
  ['🧯', 'fire extinguisher', 'fire', 'safety'],
  ['🛒', 'shopping cart', 'cart', 'shopping'],
  ['🚪', 'door', 'door'],
  ['🪞', 'mirror', 'mirror', 'reflect'],
  ['🪟', 'window', 'window'],
  ['🛋️', 'couch and lamp', 'couch', 'sofa'],
  ['🪑', 'chair', 'chair', 'seat'],
  ['🚽', 'toilet', 'toilet', 'bathroom'],
  ['🚿', 'shower', 'shower', 'bath'],
  ['🛁', 'bathtub', 'bath', 'tub'],
  ['🪥', 'toothbrush', 'toothbrush', 'teeth'],
  ['🪒', 'razor', 'razor', 'shave'],
  ['🧴', 'lotion bottle', 'lotion', 'cream'],
  ['🧷', 'safety pin', 'pin', 'safety'],
  ['🧹', 'broom', 'broom', 'sweep'],
  ['🧺', 'basket', 'basket', 'laundry'],
  ['🧻', 'roll of paper', 'toilet paper', 'paper'],
  ['🪣', 'bucket', 'bucket'],
  ['🧼', 'soap', 'soap', 'clean'],
  ['🪥', 'toothbrush', 'toothbrush'],
  ['🪦', 'headstone', 'grave', 'death', 'rip'],
  ['📦', 'package', 'box', 'package'],
  ['📬', 'open mailbox with raised flag', 'mail', 'letter'],
  ['📭', 'open mailbox with lowered flag', 'mail'],
  ['📮', 'postbox', 'mailbox'],
  ['📝', 'memo', 'note', 'write', 'memo'],
  ['📄', 'page facing up', 'document', 'paper'],
  ['📃', 'page with curl', 'document'],
  ['📑', 'bookmark tabs', 'document', 'tabs'],
  ['📊', 'bar chart', 'chart', 'data'],
  ['📈', 'chart increasing', 'chart', 'up', 'growth'],
  ['📉', 'chart decreasing', 'chart', 'down', 'loss'],
  ['📋', 'clipboard', 'clipboard'],
  ['📌', 'pushpin', 'pin', 'location'],
  ['📍', 'round pushpin', 'pin', 'location'],
  ['📎', 'paperclip', 'paperclip', 'attach'],
  ['📏', 'straight ruler', 'ruler', 'measure'],
  ['📐', 'triangular ruler', 'ruler', 'triangle'],
  ['✂️', 'scissors', 'scissors', 'cut'],
  ['🗃️', 'card file box', 'files', 'organize'],
  ['🗄️', 'file cabinet', 'cabinet', 'files'],
  ['🗑️', 'wastebasket', 'trash', 'delete'],
  ['🔍', 'magnifying glass tilted left', 'search', 'zoom', 'find'],
  ['🔎', 'magnifying glass tilted right', 'search', 'zoom'],
  ['💎', 'gem stone', 'diamond', 'gem', 'jewel'],
  ['💰', 'money bag', 'money', 'rich', 'wealth'],
  ['💵', 'dollar banknote', 'dollar', 'money'],
  ['💳', 'credit card', 'card', 'pay'],
  ['🪙', 'coin', 'coin', 'money'],
  ['📿', 'prayer beads', 'beads'],
  ['💍', 'ring', 'ring', 'engagement'],
  ['👑', 'crown', 'crown', 'king', 'queen'],
  ['👒', 'woman\'s hat', 'hat'],
  ['🎩', 'top hat', 'hat', 'formal'],
  ['🪖', 'military helmet', 'helmet', 'military'],
  ['⛑️', 'rescue worker\'s helmet', 'helmet', 'safety'],
  ['👓', 'glasses', 'glasses', 'eyewear'],
  ['🕶️', 'sunglasses', 'sunglasses', 'cool'],
  ['🥽', 'goggles', 'goggles', 'safety'],
  ['🌂', 'closed umbrella', 'umbrella', 'rain'],
  ['☂️', 'umbrella', 'umbrella', 'rain'],
  ['🎒', 'backpack', 'backpack', 'school'],
  ['👜', 'handbag', 'purse', 'bag'],
  ['👝', 'clutch bag', 'bag'],
  ['👛', 'purse', 'purse', 'wallet'],
  ['💼', 'briefcase', 'briefcase', 'work'],
  ['🌡️', 'thermometer', 'thermometer', 'temperature'],
  ['⏳', 'hourglass not done', 'hourglass', 'time', 'wait'],
  ['⌛', 'hourglass done', 'hourglass', 'time'],
  ['🎁', 'wrapped gift', 'gift', 'present'],
  ['🎀', 'ribbon', 'ribbon', 'gift'],
  ['🎈', 'balloon', 'balloon', 'party', 'celebrate'],
  ['🎉', 'party popper', 'party', 'celebrate', 'confetti'],
  ['🎊', 'confetti ball', 'party', 'celebrate'],
  ['🎋', 'tanabata tree', 'bamboo', 'japanese'],
  ['🎍', 'pine decoration', 'pine', 'japanese'],
  ['🎎', 'Japanese dolls', 'dolls', 'japanese'],
  ['🎏', 'carp streamer', 'carp', 'japanese'],
  ['🎐', 'wind chime', 'wind', 'japanese'],
  ['🧧', 'red envelope', 'lucky', 'chinese'],
  ['🎑', 'moon viewing ceremony', 'moon', 'japanese'],
  ['🎃', 'jack-o-lantern', 'halloween', 'pumpkin'],
  ['🎄', 'Christmas tree', 'christmas', 'tree'],
  ['✨', 'sparkles', 'sparkle', 'shine', 'magic'],
  ['🎆', 'fireworks', 'fireworks', 'celebrate'],
  ['🎇', 'sparkler', 'sparkler', 'fireworks'],
  ['🧨', 'firecracker', 'firecracker', 'explosion'],
  ['🎑', 'moon viewing', 'moon'],
  ['🎟️', 'admission tickets', 'ticket', 'entry'],
  ['🃏', 'joker card', 'cards'],
  ['🀄', 'mahjong', 'mahjong'],
  ['🎴', 'flower playing cards', 'cards'],
  ['🔔', 'bell', 'bell', 'alert', 'notification'],
  ['🔕', 'bell with slash', 'no bell', 'mute'],
  ['🔇', 'muted speaker', 'mute', 'silent'],
  ['🔈', 'speaker low volume', 'speaker', 'quiet'],
  ['🔉', 'speaker medium volume', 'speaker', 'volume'],
  ['🔊', 'speaker high volume', 'loud', 'volume'],
  ['📢', 'loudspeaker', 'announce', 'megaphone'],
  ['📣', 'megaphone', 'megaphone', 'cheer'],
  ['🔔', 'bell', 'notification'],
  ['🛎️', 'bellhop bell', 'bell', 'hotel'],
  ['📯', 'postal horn', 'horn', 'announce'],

  // Symbols
  ['❤️', 'red heart', 'heart', 'love', 'red'],
  ['🧡', 'orange heart', 'heart', 'orange'],
  ['💛', 'yellow heart', 'heart', 'yellow'],
  ['💚', 'green heart', 'heart', 'green'],
  ['💙', 'blue heart', 'heart', 'blue'],
  ['💜', 'purple heart', 'heart', 'purple'],
  ['🖤', 'black heart', 'heart', 'black'],
  ['🤍', 'white heart', 'heart', 'white'],
  ['🤎', 'brown heart', 'heart', 'brown'],
  ['💔', 'broken heart', 'broken', 'heartbreak', 'sad'],
  ['❣️', 'heart exclamation', 'heart', 'exclamation'],
  ['💕', 'two hearts', 'hearts', 'love'],
  ['💞', 'revolving hearts', 'hearts', 'love'],
  ['💓', 'beating heart', 'heart', 'pulse'],
  ['💗', 'growing heart', 'heart', 'love'],
  ['💖', 'sparkling heart', 'heart', 'sparkle'],
  ['💘', 'heart with arrow', 'cupid', 'love'],
  ['💝', 'heart with ribbon', 'gift', 'heart'],
  ['💟', 'heart decoration', 'heart'],
  ['☮️', 'peace symbol', 'peace'],
  ['✝️', 'latin cross', 'cross', 'christian'],
  ['☪️', 'star and crescent', 'islam', 'moon'],
  ['🕉️', 'om', 'om', 'hinduism'],
  ['☯️', 'yin yang', 'yin yang', 'balance'],
  ['✡️', 'star of David', 'jewish', 'star'],
  ['🔯', 'dotted six-pointed star', 'star'],
  ['🕎', 'menorah', 'jewish', 'hanukkah'],
  ['☦️', 'orthodox cross', 'cross', 'orthodox'],
  ['⚛️', 'atom symbol', 'atom', 'science'],
  ['🉑', 'Japanese "acceptable" button', 'japanese'],
  ['☑️', 'check box with check', 'check', 'done'],
  ['✅', 'check mark button', 'check', 'done', 'yes', 'correct'],
  ['❎', 'cross mark button', 'x', 'no', 'wrong'],
  ['❌', 'cross mark', 'x', 'no', 'wrong', 'error'],
  ['❓', 'red question mark', 'question', '?'],
  ['❔', 'white question mark', 'question'],
  ['❕', 'white exclamation mark', 'exclamation'],
  ['❗', 'red exclamation mark', 'exclamation', '!'],
  ['‼️', 'double exclamation mark', 'exclamation'],
  ['⁉️', 'exclamation question mark', 'what'],
  ['🔅', 'dim button', 'brightness', 'low'],
  ['🔆', 'bright button', 'brightness', 'high'],
  ['〽️', 'part alternation mark', 'japanese'],
  ['⚠️', 'warning', 'warning', 'caution'],
  ['🚸', 'children crossing', 'children', 'school'],
  ['♻️', 'recycling symbol', 'recycle', 'green'],
  ['✔️', 'check mark', 'check', 'done'],
  ['🔱', 'trident emblem', 'trident'],
  ['📛', 'name badge', 'badge', 'name'],
  ['🔰', 'Japanese symbol for beginner', 'beginner'],
  ['⭕', 'hollow red circle', 'circle', 'O'],
  ['🆗', 'OK button', 'ok'],
  ['🆙', 'UP! button', 'up'],
  ['🆒', 'COOL button', 'cool'],
  ['🆕', 'NEW button', 'new'],
  ['🆓', 'FREE button', 'free'],
  ['🆖', 'NG button', 'no good'],
  ['🅰️', 'A button', 'A', 'blood type'],
  ['🅱️', 'B button', 'B', 'blood type'],
  ['🆎', 'AB button', 'AB'],
  ['🅾️', 'O button', 'O'],
  ['🆑', 'CL button', 'clear'],
  ['🔴', 'red circle', 'red', 'circle'],
  ['🟠', 'orange circle', 'orange', 'circle'],
  ['🟡', 'yellow circle', 'yellow', 'circle'],
  ['🟢', 'green circle', 'green', 'circle'],
  ['🔵', 'blue circle', 'blue', 'circle'],
  ['🟣', 'purple circle', 'purple', 'circle'],
  ['⚫', 'black circle', 'black', 'circle'],
  ['⚪', 'white circle', 'white', 'circle'],
  ['🟤', 'brown circle', 'brown', 'circle'],
  ['🔶', 'large orange diamond', 'orange', 'diamond'],
  ['🔷', 'large blue diamond', 'blue', 'diamond'],
  ['🔸', 'small orange diamond', 'orange'],
  ['🔹', 'small blue diamond', 'blue'],
  ['🔺', 'red triangle pointed up', 'triangle', 'red'],
  ['🔻', 'red triangle pointed down', 'triangle', 'red', 'down'],
  ['💠', 'diamond with a dot', 'diamond'],
  ['🔘', 'radio button', 'radio'],
  ['🔲', 'black square button', 'square'],
  ['🔳', 'white square button', 'square'],
  ['▪️', 'black small square', 'square'],
  ['▫️', 'white small square', 'square'],
  ['◾', 'black medium-small square', 'square'],
  ['◽', 'white medium-small square', 'square'],
  ['◼️', 'black medium square', 'square'],
  ['◻️', 'white medium square', 'square'],
  ['⬛', 'black large square', 'square', 'black'],
  ['⬜', 'white large square', 'square', 'white'],
  ['🟥', 'red square', 'red', 'square'],
  ['🟧', 'orange square', 'orange', 'square'],
  ['🟨', 'yellow square', 'yellow', 'square'],
  ['🟩', 'green square', 'green', 'square'],
  ['🟦', 'blue square', 'blue', 'square'],
  ['🟪', 'purple square', 'purple', 'square'],
  ['🟫', 'brown square', 'brown', 'square'],
  ['🔈', 'volume low', 'sound'],
  ['🔉', 'volume medium', 'sound'],
  ['🔊', 'volume high', 'sound', 'loud'],
  ['🔀', 'shuffle tracks button', 'shuffle', 'random'],
  ['🔁', 'repeat button', 'repeat', 'loop'],
  ['🔂', 'repeat single button', 'repeat one'],
  ['▶️', 'play button', 'play'],
  ['⏩', 'fast-forward button', 'fast forward'],
  ['⏭️', 'next track button', 'next', 'skip'],
  ['⏯️', 'play or pause button', 'play pause'],
  ['◀️', 'reverse button', 'back'],
  ['⏪', 'fast reverse button', 'rewind'],
  ['⏮️', 'last track button', 'previous'],
  ['🔼', 'upwards button', 'up'],
  ['⏫', 'fast up button', 'up fast'],
  ['🔽', 'downwards button', 'down'],
  ['⏬', 'fast down button', 'down fast'],
  ['⏸️', 'pause button', 'pause'],
  ['⏹️', 'stop button', 'stop'],
  ['⏺️', 'record button', 'record'],
  ['🎦', 'cinema', 'movie', 'cinema'],
  ['🔅', 'dim button', 'low brightness'],
  ['🔆', 'bright button', 'brightness'],
  ['📶', 'antenna bars', 'signal', 'bars'],
  ['📳', 'vibration mode', 'vibrate'],
  ['📴', 'mobile phone off', 'off', 'phone'],
  ['♀️', 'female sign', 'female', 'woman'],
  ['♂️', 'male sign', 'male', 'man'],
  ['⚕️', 'medical symbol', 'medical', 'health'],
  ['♾️', 'infinity', 'infinity', 'forever'],
  ['♻️', 'recycling', 'recycle'],
  ['⚜️', 'fleur-de-lis', 'fleur'],
  ['🔱', 'trident', 'trident'],
  ['📯', 'postal horn', 'horn'],
  ['🚩', 'triangular flag', 'flag', 'red'],
  ['🎌', 'crossed flags', 'flags', 'japan'],
  ['🏴', 'black flag', 'flag', 'black'],
  ['🏳️', 'white flag', 'flag', 'white', 'surrender'],
  ['🏳️‍🌈', 'rainbow flag', 'pride', 'lgbtq', 'rainbow'],
  ['🏴‍☠️', 'pirate flag', 'pirate', 'skull'],
  ['💯', 'hundred points', '100', 'perfect', 'score'],
  ['💢', 'anger symbol', 'angry', 'mad'],
  ['💬', 'speech balloon', 'chat', 'speech', 'talk'],
  ['💭', 'thought balloon', 'think', 'thought'],
  ['💤', 'zzz', 'sleep', 'zzz', 'tired'],
  ['💥', 'collision', 'boom', 'explosion', 'pow'],
  ['💫', 'dizzy', 'dizzy', 'star'],
  ['💦', 'sweat droplets', 'sweat', 'water'],
  ['💨', 'dashing away', 'fast', 'wind'],
  ['🕳️', 'hole', 'hole'],
  ['💬', 'speech bubble', 'speech'],
  ['🗨️', 'left speech bubble', 'speech'],
  ['🗯️', 'right anger bubble', 'anger'],
  ['💬', 'speech balloon', 'talk'],
  ['💭', 'thought balloon', 'think'],
  ['🔔', 'bell', 'alert'],
  ['🔕', 'no bell', 'mute', 'silent'],
  ['🎵', 'musical note', 'music'],
  ['🎶', 'musical notes', 'music'],
  ['💲', 'heavy dollar sign', 'dollar', 'money'],
  ['💱', 'currency exchange', 'exchange', 'money'],
  ['🔃', 'clockwise vertical arrows', 'refresh', 'sync'],
  ['🔄', 'counterclockwise arrows button', 'refresh', 'reload', 'sync'],
  ['🔙', 'BACK arrow', 'back'],
  ['🔚', 'END arrow', 'end'],
  ['🔛', 'ON! arrow', 'on'],
  ['🔜', 'SOON arrow', 'soon'],
  ['🔝', 'TOP arrow', 'top'],
  ['🆔', 'ID button', 'ID'],
  ['📵', 'no mobile phones', 'no phone'],
  ['🚫', 'prohibited', 'no', 'stop', 'ban'],
  ['⛔', 'no entry', 'stop', 'no'],
  ['🛑', 'stop sign', 'stop'],
  ['🔞', 'no one under eighteen', 'adult', '18+'],
  ['📵', 'no mobile phones', 'no phone'],
  ['🔇', 'muted speaker', 'mute'],
  ['🔕', 'bell with slash', 'silent'],
  ['🚷', 'no pedestrians', 'no walking'],
  ['🚯', 'no littering', 'no trash'],
  ['🚳', 'no bicycles', 'no bikes'],
  ['🚱', 'non-potable water', 'no water'],
  ['📵', 'no mobile phones', 'no phones'],
  ['🔞', 'no under 18', '18+'],
  ['🔕', 'no bell', 'silent'],
  ['↗️', 'up-right arrow', 'diagonal', 'up'],
  ['➡️', 'right arrow', 'right'],
  ['↘️', 'down-right arrow', 'diagonal', 'down'],
  ['⬇️', 'down arrow', 'down'],
  ['↙️', 'down-left arrow', 'diagonal', 'down'],
  ['⬅️', 'left arrow', 'left'],
  ['↖️', 'up-left arrow', 'diagonal', 'up'],
  ['⬆️', 'up arrow', 'up'],
  ['↕️', 'up-down arrow', 'vertical'],
  ['↔️', 'left-right arrow', 'horizontal'],
  ['↩️', 'right arrow curving left', 'return', 'back'],
  ['↪️', 'left arrow curving right', 'forward'],
  ['⤴️', 'right arrow curving up', 'up'],
  ['⤵️', 'right arrow curving down', 'down'],
  ['🔀', 'shuffle', 'random'],
  ['🔁', 'repeat', 'loop'],
  ['🔂', 'repeat one', 'one'],
  ['🔄', 'counterclockwise', 'refresh'],
  ['🔃', 'clockwise', 'sync'],
  ['🆕', 'new', 'new'],
  ['🆙', 'up', 'up'],
  ['🆒', 'cool', 'cool'],
  ['🆓', 'free', 'free'],
  ['⭐', 'star', 'star', 'favorite'],
  ['🌟', 'glowing star', 'star', 'glow'],
  ['✨', 'sparkles', 'magic', 'shine'],
  ['⚡', 'lightning bolt', 'electric', 'flash'],
  ['💥', 'boom', 'explosion'],
  ['🔥', 'fire', 'hot', 'lit'],
  ['🌈', 'rainbow', 'colorful'],
  ['🎯', 'bullseye', 'target'],
  ['🏆', 'trophy', 'win'],
];

// Build emoji list, deduplicating by char
const seen = new Set<string>();
export const EMOJI_LIST: EmojiEntry[] = RAW
  .filter(([char]) => {
    if (seen.has(char)) return false;
    seen.add(char);
    return true;
  })
  .map(([char, name, ...keywords]) => ({ char, name, keywords }));

// Category ordering for display (index into EMOJI_LIST is implicit)
// We'll derive categories by grouping ranges
const CATEGORY_RANGES: { label: string; icon: string; start: string; end: string }[] = [
  { label: 'Smileys', icon: '😀', start: '😀', end: '😾' },
  { label: 'People', icon: '👋', start: '👋', end: '👵' },
  { label: 'Nature', icon: '🐶', start: '🐶', end: '🌀' },
  { label: 'Food', icon: '🍎', start: '🍎', end: '🥄' },
  { label: 'Activities', icon: '⚽', start: '⚽', end: '🎳' },
  { label: 'Travel', icon: '✈️', start: '✈️', end: '🗿' },
  { label: 'Objects', icon: '💡', start: '💡', end: '📯' },
  { label: 'Symbols', icon: '❤️', start: '❤️', end: '🔕' },
];

// Build category map from the raw array order
export const CATEGORIES: { label: string; icon: string; emojis: EmojiEntry[] }[] = (() => {
  // Split EMOJI_LIST into 8 buckets based on the RAW array index ranges
  // Smileys:   0   – People: after Smileys – Nature: after People – etc.
  const cutpoints = [
    { label: 'Smileys', icon: '😀' },
    { label: 'People', icon: '👋' },
    { label: 'Nature', icon: '🐶' },
    { label: 'Food', icon: '🍎' },
    { label: 'Activities', icon: '⚽' },
    { label: 'Travel', icon: '✈️' },
    { label: 'Objects', icon: '💡' },
    { label: 'Symbols', icon: '❤️' },
  ];
  // Find cut indices by first occurrence of each section start char
  const startChars = ['😀', '👋', '🐶', '🍎', '⚽', '✈️', '💡', '❤️'];
  const indices = startChars.map((c) => EMOJI_LIST.findIndex((e) => e.char === c));

  return cutpoints.map((cat, i) => {
    const start = indices[i] === -1 ? 0 : indices[i];
    const end = i + 1 < indices.length && indices[i + 1] !== -1 ? indices[i + 1] : EMOJI_LIST.length;
    return { ...cat, emojis: EMOJI_LIST.slice(start, end) };
  });
})();

// ─── Component ────────────────────────────────────────────────────────────────

type Props = {
  onSelect: (emoji: string) => void;
  onClose: () => void;
  /** If true, renders in a compact single-row mode for quick reaction picking */
  compact?: boolean;
};

export function EmojiPicker({ onSelect, onClose, compact = false }: Props) {
  const [search, setSearch] = useState('');
  const [activeCategory, setActiveCategory] = useState(0);
  const containerRef = useRef<HTMLDivElement>(null);
  const searchRef = useRef<HTMLInputElement>(null);
  const gridRef = useRef<HTMLDivElement>(null);

  // Focus search on mount
  useEffect(() => {
    searchRef.current?.focus();
  }, []);

  // Close on Escape or click outside
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose();
    }
    function onMouseDown(e: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        onClose();
      }
    }
    document.addEventListener('keydown', onKey);
    document.addEventListener('mousedown', onMouseDown);
    return () => {
      document.removeEventListener('keydown', onKey);
      document.removeEventListener('mousedown', onMouseDown);
    };
  }, [onClose]);

  const searchResults = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return null;
    return EMOJI_LIST.filter(
      (e) => e.name.includes(q) || e.keywords.some((k) => k.includes(q))
    ).slice(0, 80);
  }, [search]);

  const displayEmojis = searchResults ?? CATEGORIES[activeCategory]?.emojis ?? [];

  function handleSelect(char: string) {
    onSelect(char);
    onClose();
  }

  return (
    <div
      ref={containerRef}
      className="flex flex-col bg-ink-900 border border-white/10 rounded-2xl shadow-2xl overflow-hidden select-none"
      style={{ width: 320, maxHeight: 400 }}
      // Prevent the popover from closing when clicked inside
      onMouseDown={(e) => e.stopPropagation()}
    >
      {/* Search bar */}
      <div className="px-3 pt-3 pb-2 shrink-0">
        <div className="flex items-center gap-2 bg-ink-800/80 border border-white/[0.06] rounded-xl px-3 py-1.5">
          <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-ink-400 shrink-0">
            <circle cx="11" cy="11" r="8" />
            <line x1="21" y1="21" x2="16.65" y2="16.65" />
          </svg>
          <input
            ref={searchRef}
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search emoji…"
            className="flex-1 bg-transparent text-[13px] text-ink-100 placeholder:text-ink-400/60 outline-none min-w-0"
          />
          {search && (
            <button
              onClick={() => setSearch('')}
              className="text-ink-400 hover:text-ink-200 transition-colors shrink-0"
              tabIndex={-1}
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>
          )}
        </div>
      </div>

      {/* Category tabs (hidden when searching) */}
      {!search && (
        <div className="flex gap-0.5 px-2 pb-2 shrink-0 overflow-x-auto scrollbar-none">
          {CATEGORIES.map((cat, i) => (
            <button
              key={cat.label}
              onClick={() => setActiveCategory(i)}
              title={cat.label}
              className={`shrink-0 w-8 h-7 grid place-items-center rounded-lg text-base transition-colors
                ${activeCategory === i
                  ? 'bg-accent-violet/25 text-accent-violet'
                  : 'text-ink-300 hover:bg-white/[0.06] hover:text-ink-100'
                }`}
            >
              {cat.icon}
            </button>
          ))}
        </div>
      )}

      {/* Label */}
      <div className="px-3 pb-1 shrink-0">
        <span className="text-[10px] font-semibold text-ink-400 uppercase tracking-wider">
          {search ? `Results for "${search}"` : CATEGORIES[activeCategory]?.label}
        </span>
      </div>

      {/* Emoji grid */}
      <div
        ref={gridRef}
        className="flex-1 overflow-y-auto px-2 pb-2"
        style={{ minHeight: 0 }}
      >
        {displayEmojis.length === 0 ? (
          <div className="py-6 text-center text-[12px] text-ink-400">No emoji found</div>
        ) : (
          <div className="grid" style={{ gridTemplateColumns: 'repeat(8, 1fr)', gap: 2 }}>
            {displayEmojis.map((e) => (
              <button
                key={e.char + e.name}
                onClick={() => handleSelect(e.char)}
                title={e.name}
                className="h-9 grid place-items-center text-xl rounded-lg hover:bg-white/[0.08] transition-colors hover:scale-110 transition-transform"
              >
                {e.char}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
